# Generated by Django 3.0.9 on 2020-08-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='null', max_length=254),
            preserve_default=False,
        ),
    ]
